version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: morele_app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./php.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on:
      - db
    networks:
      - morele_network

  web:
    image: nginx:alpine
    container_name: morele_web
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - morele_network

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: morele_movies
      MYSQL_USER: morele_admin
      MYSQL_PASSWORD: morele_password
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - morele_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel_phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - 8081:80
    depends_on:
      - db
    networks:
      - morele_network

volumes:
  dbdata:

networks:
  morele_network:
    driver: bridge
